load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "coefs",
    srcs = [],
    hdrs = glob(["*_coefs.hpp"]),
    deps = ["//vmfunctions:root"],
    visibility = ["//visibility:public"],
)